version: '3.8'

services:
  # Твій Flask додаток
  web:
    build: .
    container_name: sneaker_store_backend
    restart: always
    environment:
      - DATABASE_PATH=/app/data/shop.db
    volumes:
      - sqlite_data:/app/data  # Зберігаємо БД, щоб не зникала
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/api/products"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Веб-сервер Nginx
  nginx:
    image: nginx:alpine
    container_name: sneaker_store_nginx
    restart: always
    ports:
      - "80:80"  # Відкриваємо сайт на стандартному порту
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  sqlite_data: